version: '3'

services:
  apache:
    build:
      dockerfile: Dockerfile
      context: .
    image: mmazoni/php7-apache2-dockerfile
    container_name: php7-apache2
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./webapp:/var/www/html
    depends_on:
      - mysqldb
    links:
      - mysqldb

  mysqldb:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=enquete
      - MYSQL_DATABASE=enquete